#!/bin/sh

export NIX_MY_PKGS='/home/matej/workarea/nixpkgs'
export NIX_USER_PROFILE_DIR='/nix/var/nix/profiles/per-user/matej'

export NIX_PATH="nixpkgs=$NIX_MY_PKGS:nixos=$NIX_MY_PKGS/nixos:nixos-config=/etc/nixos/configuration.nix:services=/etc/nixos/services"

alias nixmy-profile="nix-env -f '$NIX_MY_PKGS' -p $NIX_USER_PROFILE_DIR/"
alias nixmy-py27="nix-env -f '$NIX_MY_PKGS' -p $NIX_USER_PROFILE_DIR/py27 -i py27"
alias nixmy-cd="cd '$NIX_MY_PKGS'"

alias nix-env="nix-env -f '$NIX_MY_PKGS'"

# Sudo helper
_asroot() {
  case `whoami` in
    root)
      echo "" ;;
    *)
      echo "sudo -H " ;;
  esac
}

function trytorun {
    "$@"
    local rc=$?
    if [ $rc -ne 0 ]; then
        echo "ERROR with \"$1\""
        exit $rc
    fi
    return $rc
}

nixmy-rebuild() { `_asroot` nixos-rebuild -I $NIX_MY_PKGS "$@" ; }

# Print latest Hydra's revision
nixmy-revision() {
  local rev=`wget -q  -S --output-document - http://nixos.org/releases/nixos/channels/nixos-unstable 2>&1 |
    grep Location | head -n 1 | awk -F '.' '{print $4}'`
  printf "%s" $rev
}

nixmy-update() {
    trytorun cd $NIX_MY_PKGS

    local diffoutput="`git --no-pager diff`"
    if [ -z $diffoutput ]; then
        echo "git diff is empty, preceding ..."
        trytorun git checkout master
        trytorun git pull --rebase upstream master
        trytorun git checkout "local"
        local rev=`nixmy-revision`
        echo "rebasing 'local' to '$rev'"
        trytorun git rebase $rev
    else
        git status
        echo "STAGE IS NOT CLEAN! CLEAR IT BEFORE UPDATE!"
        return 1
    fi

}